### ISSUE TITLE
MINOR: Required Inputs for Form not Accurate

### ISSUE THREAD

**Issue by kevin-chiu** [info442-group-7/HelpOut#34] opened 2020-06-05 22:45 UTC
Describe the bug
An address is required in the signup page, but is not indicated with a red star.

To Reproduce

Click on sign up
A form asking to fill out the credentials with necessary information will be 
Fill out all inputs except "Address"
Click Register.
The account setup process will be incomplete, stating "Your full address is required" 4x

Expected behavior
I expected the form to be complete and the account creation process to be fulfilled.

Screenshots
![image](https://user-images.githubusercontent.com/31137647/83927912-1a0e1780-a743-11ea-917a-a767b5b754df.png)

**Comment by jamiekiok** [comment] 2020-06-11 01:25
Thanks for your feedback and catching this issue! 

Marking this as a duplicate, as it has been fixed/closed in issue #33 .

**Comment by jamiekiok** [comment] 2020-06-11 01:27
Duplicate of #33 .

**Closed** 2020-06-11 01:27 UTC
